services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    build: ./back
    env_file: .env
    command:
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn typeorm migration:run -d src/data-source.ts'
    volumes:
      - ./back:/code
    depends_on:
      - db
    
  api:
    build: ./back
    env_file: .env
    command:
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn dev'
    volumes:
      - ./back:/code
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
      - migrations

  front:
    build: ./front
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
      - migrations
      - api


volumes:
  pgdata:
  